### ISSUE TITLE
Chat Bot is not opening in android studio??

### ISSUE THREAD

**Issue by vibhav16** [preethi123/Simple-Android-Chat-Bot#1]
Why android studio not detecting this app?

**Comment by unicorncoderforever** [comment]
Can you tell more about the error ?

**Comment by vibhav16** [comment]
It says android module is missing.

**Comment by unicorncoderforever** [comment]
@vibhav16  I tried downloading this project and importing it. It works fine. 
Note : import AliceSample Folder not the outer folder. Try this . And download if any gradle dependency is there.

**Comment by vibhav16** [comment]
👍

**Comment by unicorncoderforever** [comment]
@vibhav16  if this has helped can you please close the issue
